baseURL = "https://ulsonhu.cn/"
locale = "zh-cn"
defaultContentLanguage = "zh"
title = "Julio"
paginate = 5
hasCJKLanguage = true
summaryLength = 120

[pagination]
  pagerSize = 5
enableRobotsTXT = true
enableGitInfo = false
disablePathToLower = true

[params]
  author = "Watson Hu"
  tagline = "Lying in the gutter, but looking at the stars."
  description = "Lying in the gutter, but looking at the stars."
  keywords = ["统计学", "机器学习", "前端", "博客"]

[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 1
[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 2
[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 3
[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 4
[[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    lineNos = false
    guessSyntax = true
